### ISSUE TITLE
use wp.template

### ISSUE THREAD

**Issue by rohmann** [aut0poietic/wp-admin-modal-example#3]
Thanks for this! Was handy to see how you broke down the views for a recent project.

One thing to consider is using wp.template instead of _.template for your template loader. I just added all my templates the the footer, but anytime PHP runs the template file it can cause issues on servers that have ASP tags enabled. Using the WordPress helper function, and updating the templates to support their mustache style interpolation will address this.

https://github.com/WordPress/WordPress/blob/master/wp-includes/js/wp-util.js

**Comment by aut0poietic** [comment]
Keep trying to get back to this. Been using it in production projects but this old example keeps getting forgotten. Hafta carve out some time : )

Thanks for the heads up!

**Comment by aut0poietic** [comment]
Now in v1.1.0
